version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000" # Change to port 3000 for Next.js
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "3001:3001" # If your backend runs on a different port
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appraisal_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

