version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app/backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/appraisal_db
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appraisal_db
      - POSTGRES_HOST=db
volumes:
  postgres_dev_data:

