# docker-compose.prod.yml
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/appraisal_db
      - JWT_SECRET=your_super_secret_value_here
      - FIREBASE_TYPE=service_account
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appraisal_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./backend/credentials:/app/credentials:ro
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: database/Dockerfile.prod
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/certs/server.crt:/etc/postgresql/server.crt
      - ./database/certs/server.key:/etc/postgresql/server.key
    environment:
      - NODE_ENV=production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appraisal_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_prod_data: