# docker-compose.prod.yml
version: '3.8'

services:
  frontend:
    build:
      context: ..                              # ✅ Root context so it can access tsconfig.json
      dockerfile: docker/frontend/Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000  # ✅ Recommend using actual internal/external API URL
    depends_on:
      - backend

  backend:
    build:
      context: ..                              # ✅ Root context to copy root-level tsconfig.json
      dockerfile: docker/backend/Dockerfile.prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/property_appraisal
    depends_on:
      - db

  db:
    build:
      context: ../database                     # ✅ Points to actual database/ folder
      dockerfile: ../docker/database/Dockerfile.prod
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    environment:
      - NODE_ENV=production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appraisal_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

volumes:
  postgres_prod_data:
