# docker-compose.prod.yml
version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api.yourdomain.com
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/backend/Dockerfile.prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/property_appraisal
    depends_on:
      - db

  db:
    build:
      context: ../database   # Ensure this points to `database/`
      dockerfile: ../docker/database/Dockerfile.prod
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=property_appraisal

volumes:
  postgres_prod_data:
